// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxKQCS7BCr6pZWPX1lgLFXXYzvooSgfk',
    appId: '1:259604529390:web:6ad93f7eec52baedb0f3ff',
    messagingSenderId: '259604529390',
    projectId: 'test-17cc0',
    authDomain: 'test-17cc0.firebaseapp.com',
    storageBucket: 'test-17cc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5n8eam6qnLNvxXo1tzIBWACgnWbrfwek',
    appId: '1:259604529390:android:6bbd03c592c6d105b0f3ff',
    messagingSenderId: '259604529390',
    projectId: 'test-17cc0',
    storageBucket: 'test-17cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0YcXdU2OP24y26nDtC3eUW_f6Wvqn-7c',
    appId: '1:259604529390:ios:7f4c9e5078dd9123b0f3ff',
    messagingSenderId: '259604529390',
    projectId: 'test-17cc0',
    storageBucket: 'test-17cc0.appspot.com',
    iosClientId: '259604529390-6936rf3ec1113shrke6u6ptabj7rsj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0YcXdU2OP24y26nDtC3eUW_f6Wvqn-7c',
    appId: '1:259604529390:ios:7f4c9e5078dd9123b0f3ff',
    messagingSenderId: '259604529390',
    projectId: 'test-17cc0',
    storageBucket: 'test-17cc0.appspot.com',
    iosClientId: '259604529390-6936rf3ec1113shrke6u6ptabj7rsj5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
